$axure.loadCurrentPage({
  "url":"faq.html",
  "generationDate":new Date(1428891471340.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1b9058f371654dfe894e407103194aa2",
    "type":"Axure:Page",
    "name":"FAQ",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"08e76dac1adb4ac1a34b9554c90cb3e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d43a01150fd4da6a5e20c5d7082943e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/faq/u0.png"}},
{
          "id":"7440ba16e5b94bb59c89c04eef092cf2",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb83a7a07335473f9feb280b360e91b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":20},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open validate in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"validate.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fdd43289d6944a5a9e1013055ca360f",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":840},
            "size":{
              "width":110,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0f911cde23043b7b29424b75222354f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":840},
                "size":{
                  "width":110,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open problem Contact us in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"problem_contact_us.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb260112163d4411a57dd2907e25fe48",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFF,
              "opacity":0},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":195,
              "y":293},
            "size":{
              "width":50,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74b03c0d1da84d2e9e70303fb1e7945f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF,
                  "opacity":0},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":195,
                  "y":293},
                "size":{
                  "width":50,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Dynamic Panel)",
                      "objectsToFades":[{
                          "objectPath":["2e0b81146fed4709b0a3d131bae24f78"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e0b81146fed4709b0a3d131bae24f78",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "size":{
              "width":750,
              "height":1334},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"208c0895d0df442e9765b3f32d039633",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"454eacc799d64e4c8948649b96d2237b",
                  "label":"Rectangle",
                  "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":1334},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46842854554c43f082d9c741d8ebc7f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":1334},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/faq/rectangle_u9.png"}},
{
                  "id":"95d60b3995354ac1b651d46d51ca08b1",
                  "label":"Rectangle",
                  "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00C9FF},
                    "size":{
                      "width":750,
                      "height":160},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d225ef93b039423eae5306027d83ce78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF00C9FF},
                        "size":{
                          "width":750,
                          "height":160},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/faq/rectangle_u11.png"}},
{
                  "id":"8d3beedfa3464c05876c73871f67d313",
                  "label":"",
                  "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":66,
                      "y":170},
                    "size":{
                      "width":684,
                      "height":1160}},
                  "adaptiveStyles":{
},
                  "scrollbars":"verticalAsNeeded",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"79bf151140f74bc9907a48fb1d8b780f",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"be4ea8f034e64bcea824a5c62aebf467",
                          "label":"Rectangle",
                          "parentDynamicPanel":"8d3beedfa3464c05876c73871f67d313",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":750,
                              "height":3510},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"eb3b921de0c24db49a447a9555a453f0",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8d3beedfa3464c05876c73871f67d313",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":750,
                                  "height":3510},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/faq/rectangle_u14.png"}},
{
                          "id":"bb1d1c54e7cd43859491bbbc3896a773",
                          "label":"Header 1",
                          "parentDynamicPanel":"8d3beedfa3464c05876c73871f67d313",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"36px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "lineSpacing":"60px",
                            "location":{
                              "x":120,
                              "y":0},
                            "size":{
                              "width":225,
                              "height":3510},
                            "rotation":"0",
                            "textRotation":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6ae355f373104003a98d0f9ef4a689c6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8d3beedfa3464c05876c73871f67d313",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"36px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF999999,
                                  "opacity":1},
                                "lineSpacing":"60px",
                                "location":{
                                  "x":120,
                                  "y":0},
                                "size":{
                                  "width":225,
                                  "height":3510},
                                "rotation":"0",
                                "textRotation":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"94e24f07356140999ac5ee9adbb5a755",
                          "label":"Header 1",
                          "parentDynamicPanel":"8d3beedfa3464c05876c73871f67d313",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"36px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "lineSpacing":"60px",
                            "location":{
                              "x":355,
                              "y":0},
                            "size":{
                              "width":240,
                              "height":3510},
                            "rotation":"0",
                            "textRotation":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"bced9bfcbc974f6a8403e150baa6b093",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8d3beedfa3464c05876c73871f67d313",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"36px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF999999,
                                  "opacity":1},
                                "lineSpacing":"60px",
                                "location":{
                                  "x":355,
                                  "y":0},
                                "size":{
                                  "width":240,
                                  "height":3510},
                                "rotation":"0",
                                "textRotation":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"f4ba879abe954d1097604a25b96ea463",
                  "label":"Header 2",
                  "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"40px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":156,
                      "y":102},
                    "size":{
                      "width":550,
                      "height":58},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f88c4f45d31468ea6669350d3bf8838",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"40px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":156,
                          "y":102},
                        "size":{
                          "width":550,
                          "height":58},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7c0ca7fd6af8466b8380a5af3e3fef73",
                  "label":"Header 1",
                  "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":20},
                    "size":{
                      "width":40,
                      "height":55},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a5400d114eb4cb996799fcd967aff12",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e0b81146fed4709b0a3d131bae24f78",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"48px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":20},
                        "size":{
                          "width":40,
                          "height":55},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide (Dynamic Panel)",
                              "objectsToFades":[{
                                  "objectPath":["2e0b81146fed4709b0a3d131bae24f78"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0864cb7acdcc4995866628c8d508572b",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":540,
              "y":20},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055681c8941d4de49250cb28fff29731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":540,
                  "y":20},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open report problem in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"report_problem.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "08e76dac1adb4ac1a34b9554c90cb3e9":{
      "scriptId":"u0"},
    "4d43a01150fd4da6a5e20c5d7082943e":{
      "scriptId":"u1"},
    "7440ba16e5b94bb59c89c04eef092cf2":{
      "scriptId":"u2"},
    "bb83a7a07335473f9feb280b360e91b9":{
      "scriptId":"u3"},
    "1fdd43289d6944a5a9e1013055ca360f":{
      "scriptId":"u4"},
    "e0f911cde23043b7b29424b75222354f":{
      "scriptId":"u5"},
    "eb260112163d4411a57dd2907e25fe48":{
      "scriptId":"u6"},
    "74b03c0d1da84d2e9e70303fb1e7945f":{
      "scriptId":"u7"},
    "2e0b81146fed4709b0a3d131bae24f78":{
      "scriptId":"u8"},
    "454eacc799d64e4c8948649b96d2237b":{
      "scriptId":"u9"},
    "46842854554c43f082d9c741d8ebc7f9":{
      "scriptId":"u10"},
    "95d60b3995354ac1b651d46d51ca08b1":{
      "scriptId":"u11"},
    "d225ef93b039423eae5306027d83ce78":{
      "scriptId":"u12"},
    "8d3beedfa3464c05876c73871f67d313":{
      "scriptId":"u13"},
    "be4ea8f034e64bcea824a5c62aebf467":{
      "scriptId":"u14"},
    "eb3b921de0c24db49a447a9555a453f0":{
      "scriptId":"u15"},
    "bb1d1c54e7cd43859491bbbc3896a773":{
      "scriptId":"u16"},
    "6ae355f373104003a98d0f9ef4a689c6":{
      "scriptId":"u17"},
    "94e24f07356140999ac5ee9adbb5a755":{
      "scriptId":"u18"},
    "bced9bfcbc974f6a8403e150baa6b093":{
      "scriptId":"u19"},
    "f4ba879abe954d1097604a25b96ea463":{
      "scriptId":"u20"},
    "8f88c4f45d31468ea6669350d3bf8838":{
      "scriptId":"u21"},
    "7c0ca7fd6af8466b8380a5af3e3fef73":{
      "scriptId":"u22"},
    "5a5400d114eb4cb996799fcd967aff12":{
      "scriptId":"u23"},
    "0864cb7acdcc4995866628c8d508572b":{
      "scriptId":"u24"},
    "055681c8941d4de49250cb28fff29731":{
      "scriptId":"u25"}}});