$axure.loadCurrentPage({
  "url":"validate.html",
  "generationDate":new Date(1428891470358.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"adae1bf657f24e9fa5ff85fd938ce7e3",
    "type":"Axure:Page",
    "name":"validate",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6167b847a6fc4a91bf654b540a6a4309",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e8e9b2694ad4f96b671bee5b666eb84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/validate/u0.png"}},
{
          "id":"d1a4cfd79f2e440287379e4e40add037",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":387,
              "y":520},
            "size":{
              "width":163,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f5a01fca78e4d1baa6a502656bcc674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":387,
                  "y":520},
                "size":{
                  "width":163,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open call justalk in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"call_justalk.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb08eb5c72554f758d09d92af0749877",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":180,
              "y":520},
            "size":{
              "width":170,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd25904013d045b5bc790e2b5d5f4ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":180,
                  "y":520},
                "size":{
                  "width":170,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Dynamic Panel)",
                      "objectsToFades":[{
                          "objectPath":["58128bf144294c2394a61940bcd476d7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"087cecfd1c3242ea88f7f85491000b0e",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":730},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07266ca6aeba46d8a391dd7663429ae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":550,
                  "y":730},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open FAQ in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"faq.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d5a48edef5048189d8d02a9fbca37db",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":31,
              "y":20},
            "size":{
              "width":150,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7834bc6bbbd948979a2378f10342bf71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":31,
                  "y":20},
                "size":{
                  "width":150,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open JusTalk in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"justalk.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ffc20ca11c848d996cafca923c1139c",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":90,
              "y":630},
            "size":{
              "width":570,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87edd55ca1244b8ab9ad05462f47b5df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":90,
                  "y":630},
                "size":{
                  "width":570,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open entering main in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"entering_main.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58128bf144294c2394a61940bcd476d7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "size":{
              "width":750,
              "height":1334},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"18e7e78df315430f852f9e095dfea17c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4a7eb87b8e5e432c913a489fc6c8b969",
                  "label":"resend code",
                  "parentDynamicPanel":"58128bf144294c2394a61940bcd476d7",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":1334}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de4ec746fdfd4f89aeb0ade4ed3d8181",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"58128bf144294c2394a61940bcd476d7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":1334}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/validate/resend_code_u13.png"}},
{
                  "id":"6021b853dd584781a2bc0aa1f976ccde",
                  "label":"Rectangle",
                  "parentDynamicPanel":"58128bf144294c2394a61940bcd476d7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":80,
                      "y":584},
                    "size":{
                      "width":590,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e532140179314a2aad66e83dbccc1cc1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"58128bf144294c2394a61940bcd476d7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":80,
                          "y":584},
                        "size":{
                          "width":590,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide (Dynamic Panel)",
                              "objectsToFades":[{
                                  "objectPath":["58128bf144294c2394a61940bcd476d7"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"7aebefe60b4a48a1ab81ea1e3c706abb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":194.5,
              "y":980},
            "size":{
              "width":281,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f5ccf7823df438684b1386999843879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":194.5,
                  "y":980},
                "size":{
                  "width":281,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open after 3 attempts in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"after_3_attempts.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cbb3459ada8486090a4c5d2e9b9a213",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":1005},
            "size":{
              "width":10,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/validate/u19_line.png"}},
{
          "id":"de7668e921e741569f9189e06b8be0dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFCC00,
              "opacity":1},
            "location":{
              "x":227,
              "y":1064},
            "size":{
              "width":217,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e991ff82ca4bf28d0881e0bf58b206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":1064},
                "size":{
                  "width":217,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6167b847a6fc4a91bf654b540a6a4309":{
      "scriptId":"u0"},
    "9e8e9b2694ad4f96b671bee5b666eb84":{
      "scriptId":"u1"},
    "d1a4cfd79f2e440287379e4e40add037":{
      "scriptId":"u2"},
    "6f5a01fca78e4d1baa6a502656bcc674":{
      "scriptId":"u3"},
    "cb08eb5c72554f758d09d92af0749877":{
      "scriptId":"u4"},
    "fd25904013d045b5bc790e2b5d5f4ee3":{
      "scriptId":"u5"},
    "087cecfd1c3242ea88f7f85491000b0e":{
      "scriptId":"u6"},
    "07266ca6aeba46d8a391dd7663429ae0":{
      "scriptId":"u7"},
    "7d5a48edef5048189d8d02a9fbca37db":{
      "scriptId":"u8"},
    "7834bc6bbbd948979a2378f10342bf71":{
      "scriptId":"u9"},
    "7ffc20ca11c848d996cafca923c1139c":{
      "scriptId":"u10"},
    "87edd55ca1244b8ab9ad05462f47b5df":{
      "scriptId":"u11"},
    "58128bf144294c2394a61940bcd476d7":{
      "scriptId":"u12"},
    "4a7eb87b8e5e432c913a489fc6c8b969":{
      "scriptId":"u13"},
    "de4ec746fdfd4f89aeb0ade4ed3d8181":{
      "scriptId":"u14"},
    "6021b853dd584781a2bc0aa1f976ccde":{
      "scriptId":"u15"},
    "e532140179314a2aad66e83dbccc1cc1":{
      "scriptId":"u16"},
    "7aebefe60b4a48a1ab81ea1e3c706abb":{
      "scriptId":"u17"},
    "3f5ccf7823df438684b1386999843879":{
      "scriptId":"u18"},
    "0cbb3459ada8486090a4c5d2e9b9a213":{
      "scriptId":"u19"},
    "de7668e921e741569f9189e06b8be0dc":{
      "scriptId":"u20"},
    "13e991ff82ca4bf28d0881e0bf58b206":{
      "scriptId":"u21"}}});